name: Feature Request 💡
description: Have a new idea or feature? Let us know...
title: "[FEATURE] <brief description>"
labels: ["status: awaiting triage"]

body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Is this feature already requested?
      description: Ensure this feature hasn't been suggested before.
      options:
        - label: I have checked "open" and "closed" issues, and this is not a duplicate.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Missing Functionality
      description: Briefly describe the problem or the missing functionality that this feature would address.
      placeholder: "For ex: I often encounter [specific problem] when using [current feature or lack thereof]. Implementing this feature would improve [specific aspect or workflow] by [explain how it will help]."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Feature Description
      description: Describe the feature you're suggesting and how it would solve the problem. Include any relevant details or references.
      placeholder: "For ex: I suggest adding [describe the feature] that will [explain its impact]. This feature could be similar to [mention any known implementations or inspirations], which helps by [describe how it benefits the users]."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach any screenshots that might help illustrate the feature or its need  (Optional).
      placeholder: "If applicable, drag and drop images here or click to upload. Screenshots can help clarify your suggestion by showing the current issue or how the feature might look."
    validations:
      required: false

  - type: dropdown
    id: work_on_issue
    attributes:
      label: Would you like to work on this feature?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation Plan
      description: If you selected "Yes" above, briefly describe how you plan to implement this feature (Optional).
      placeholder: "For example: I plan to start by [outline your steps], using [mention any tools, libraries, or frameworks]. This will help ensure the feature is developed efficiently and meets the intended purpose."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please ensure you've filled out all the required sections to help us evaluate your suggestion effectively.
