name: Code Quality and Formatting

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

#      - name: Check for formatting issues
#        run: |
#          npm install prettier --save-dev
#          npx prettier --check '**/*.{ts,tsx,js,jsx,css,scss,md,html,json}'
